//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приемная_комиссия
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int IDList { get; set; }
        public Nullable<int> IDSpec { get; set; }
        public Nullable<int> IDEntrant { get; set; }
        public string FormStudy { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual Entrant Entrant { get; set; }
        public virtual Spaciality Spaciality { get; set; }
    }
}
