//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приемная_комиссия
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCEntities : DbContext
    {
        public PCEntities()
            : base("name=PCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entrant> Entrant { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Spaciality> Spaciality { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
