//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приемная_комиссия
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spaciality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spaciality()
        {
            this.List = new HashSet<List>();
        }
    
        public int IDSpec { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDFac { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlaceBudget { get; set; }
        public Nullable<int> PlaceCommerce { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List> List { get; set; }
    }
}
